//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


namespace XperienceCommunity.CSVImport
{
    public partial class CSVImport
    {

        /// <summary>
        /// pnlSelectTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlSelectTable;

        /// <summary>
        /// ddlClasses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ddlClasses;

        /// <summary>
        /// pnlGetOrUploadCSV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlGetOrUploadCSV;

        /// <summary>
        /// btnGetCSV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnGetCSV;

        /// <summary>
        /// fileCSV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fileCSV;

        /// <summary>
        /// btnParseCSV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnParseCSV;

        /// <summary>
        /// pnlCSVMapAndSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlCSVMapAndSettings;

        /// <summary>
        /// cbxTreatNullAsNull control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbxTreatNullAsNull;

        /// <summary>
        /// ddlInsertMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ddlInsertMode;

        /// <summary>
        /// ddlIdentifierField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ddlIdentifierField;

        /// <summary>
        /// ddlUpdateMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ddlUpdateMode;

        /// <summary>
        /// ddlUpdateIndicator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ddlUpdateIndicator;

        /// <summary>
        /// ddlDeleteMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ddlDeleteMode;

        /// <summary>
        /// ddlDeleteIndicator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ddlDeleteIndicator;

        /// <summary>
        /// plcFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plcFields;

        /// <summary>
        /// btnProcessImport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnProcessImport;

        protected global::System.Web.UI.WebControls.DropDownList ddlDelimiter;
    }

}